### ISSUE TITLE
Consider using a dedicated Embedding model

### ISSUE THREAD

**Issue by tzolov** [AtomicJar/spring-ai-demo#4]
My experience show that when using LLM models for embedding the performance is extremely slow. 

You can consider using a dedicated [Ollama embedding model](https://ollama.com/search?c=embedding) and change the [config](https://github.com/AtomicJar/spring-ai-demo/blob/e0fa56d252a27e64fd6991cb839ce6c18c1f3cb4/src/main/resources/application.properties#L2-L5).

**Comment by eddumelendez** [comment]
Hi @tzolov, thanks. The suggestion has been applied https://github.com/AtomicJar/spring-ai-demo/blob/main/src/test/resources/application.properties
